# Form implementation generated from reading ui file '/home/hidden/Escritorio/EvaSystem1.0/QdialogsUi/initsesion.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InicioSecion(object):
    def setupUi(self, InicioSecion):
        InicioSecion.setObjectName("InicioSecion")
        InicioSecion.resize(369, 469)
        InicioSecion.setMinimumSize(QtCore.QSize(369, 469))
        InicioSecion.setMaximumSize(QtCore.QSize(798, 832))
        InicioSecion.setStyleSheet("*{\n"
"    background-color: rgb(24,24,36);\n"
"    border: none;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border:2px solid rgb(234,190,63);\n"
"    height: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    background-color:rgb(234,190,63);\n"
"    color: #000;\n"
"}\n"
"QLineEdit{\n"
"    border-bottom: 1px solid rgb(234,190,63);\n"
"    height: 30px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: #525252\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(InicioSecion)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(InicioSecion)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 120))
        self.frame_2.setMaximumSize(QtCore.QSize(369, 170))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_paper = QtWidgets.QLabel(self.frame_5)
        self.lbl_paper.setText("")
        self.lbl_paper.setPixmap(QtGui.QPixmap(":/cct/remove_paper.png"))
        self.lbl_paper.setScaledContents(True)
        self.lbl_paper.setObjectName("lbl_paper")
        self.horizontalLayout_3.addWidget(self.lbl_paper)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.horizontalLayout.addWidget(self.frame_6)
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_sesion_minimize = QtWidgets.QPushButton(self.frame_10)
        self.btn_sesion_minimize.setStyleSheet("height:20px;")
        self.btn_sesion_minimize.setText("")
        self.btn_sesion_minimize.setObjectName("btn_sesion_minimize")
        self.horizontalLayout_4.addWidget(self.btn_sesion_minimize)
        self.btn_sesion_destroy = QtWidgets.QPushButton(self.frame_10)
        self.btn_sesion_destroy.setStyleSheet("height:20px;")
        self.btn_sesion_destroy.setText("")
        self.btn_sesion_destroy.setObjectName("btn_sesion_destroy")
        self.horizontalLayout_4.addWidget(self.btn_sesion_destroy)
        self.horizontalLayout.addWidget(self.frame_10, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 600))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Input_user = QtWidgets.QLineEdit(self.frame_7)
        self.Input_user.setInputMask("")
        self.Input_user.setObjectName("Input_user")
        self.verticalLayout_5.addWidget(self.Input_user)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Input_pass = QtWidgets.QLineEdit(self.frame_8)
        self.Input_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Input_pass.setObjectName("Input_pass")
        self.verticalLayout_6.addWidget(self.Input_pass)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.btn_init_sesion = QtWidgets.QPushButton(self.frame_3)
        self.btn_init_sesion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_init_sesion.setObjectName("btn_init_sesion")
        self.verticalLayout_3.addWidget(self.btn_init_sesion)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_7.addWidget(self.textEdit)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(InicioSecion)
        QtCore.QMetaObject.connectSlotsByName(InicioSecion)

    def retranslateUi(self, InicioSecion):
        _translate = QtCore.QCoreApplication.translate
        InicioSecion.setWindowTitle(_translate("InicioSecion", "InicioSecion"))
        self.label_2.setText(_translate("InicioSecion", "Paper Company  "))
        self.label_6.setText(_translate("InicioSecion", "System"))
        self.label_5.setText(_translate("InicioSecion", "Eva Version 1.0"))
        self.label_3.setText(_translate("InicioSecion", "Introduce Tu Usuario"))
        self.Input_user.setPlaceholderText(_translate("InicioSecion", "tu usuario"))
        self.label_4.setText(_translate("InicioSecion", "Tu Contraseña"))
        self.Input_pass.setPlaceholderText(_translate("InicioSecion", "Introduce tu contraseña"))
        self.btn_init_sesion.setText(_translate("InicioSecion", "Iniciar sesion"))
        self.textEdit.setHtml(_translate("InicioSecion", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Este sistema Le ayudara a usted para Dirigir Y manejar de manera mas eficiente su empresa ¡¡¡Bienvenido!!!!</p></body></html>"))
